### ISSUE TITLE
psc 0.8.0.0 generates wrong JS instance name in Unit/index.js

### ISSUE THREAD

**Issue by brakmic** [paf31/purescript-preface#2]
Hi,

I get this error when running **pulp test**

```
* Build successful.
* Running tests...
D:\src\purescript\purescript-preface\output\Unit\index.js:10
var unit = Unit_1.Unit.value;
           ^

ReferenceError: Unit_1 is not defined
    at Object.<anonymous> (D:\src\purescript\purescript-preface\output\Unit\index.js:10:12)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (D:\src\purescript\purescript-preface\output\Task\index.js:4:12)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
 * ERROR: Subcommand terminated with exit code 1
```

This is my **output/Unit/index.js**:

```
 // Generated by psc version 0.8.0.0
"use strict";
var Unit = (function () {
    function Unit() {

    };
    Unit.value = new Unit();
    return Unit;
})();
var unit = Unit_1.Unit.value;
module.exports = {
    unit: unit
};
```

There's a superfluous instance *Unit_1*. After having removed it my next **pulp test** succeeded:

```
D:\src\purescript\purescript-preface>pulp test
* Building project in D:\src\purescript\purescript-preface
psc: No files found using pattern: bower_components\purescript-*\src/**/*.purs
psc: No files found using pattern: bower_components\purescript-*\src/**/*.js
psc: No files found using pattern: test/**/*.js
* Build successful.
* Running tests...
Hello, World!
Done.
* Tests OK.

```

**Comment by paf31** [comment]
Yes, this is a known compiler bug which will be fixed before 0.8 proper.
